# TCL File Generated by Component Editor 21.1
# for vga_ball peripheral

package require -exact qsys 16.0

# module vga_ball
set_module_property DESCRIPTION "VGA Ball Peripheral"
set_module_property NAME vga_ball
set_module_property VERSION 1.0
set_module_property GROUP "VGA"
set_module_property DISPLAY_NAME "VGA Ball"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property TOP_LEVEL_HDL_FILE vga_ball.sv
set_module_property TOP_LEVEL_HDL_MODULE vga_ball
set_module_property VALIDATION_CALLBACK validate

# Device tree assignments (these get wiped on re-analysis -- verify after each edit)
set_module_assignment embeddedsw.dts.vendor "csee4840"
set_module_assignment embeddedsw.dts.name "vga_ball"
set_module_assignment embeddedsw.dts.group "vga"

#
# parameters
#

#
# connection point clk
#
add_interface clk clock end
set_interface_property clk clockRate 50000000
set_interface_property clk ENABLED true
add_interface_port clk clk clk Input 1

#
# connection point reset
#
add_interface reset reset end
set_interface_property reset associatedClock clk
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
add_interface_port reset reset reset Input 1

#
# connection point s1 (Avalon Memory-Mapped Slave)
#
add_interface s1 avalon end
set_interface_property s1 addressUnits WORDS
set_interface_property s1 associatedClock clk
set_interface_property s1 associatedReset reset
set_interface_property s1 bitsPerSymbol 8
set_interface_property s1 burstOnBurstBoundariesOnly false
set_interface_property s1 burstcountUnits WORDS
set_interface_property s1 explicitAddressSpan 0
set_interface_property s1 holdTime 0
set_interface_property s1 linewrapBursts false
set_interface_property s1 maximumPendingReadTransactions 0
set_interface_property s1 maximumPendingWriteTransactions 0
set_interface_property s1 readLatency 0
set_interface_property s1 readWaitTime 1
set_interface_property s1 setupTime 0
set_interface_property s1 timingUnits Cycles
set_interface_property s1 writeWaitTime 0
set_interface_property s1 ENABLED true

add_interface_port s1 writedata writedata Input 16
add_interface_port s1 write write Input 1
add_interface_port s1 chipselect chipselect Input 1
add_interface_port s1 address address Input 1

#
# connection point vga (conduit)
#
add_interface vga conduit end
set_interface_property vga associatedClock clk
set_interface_property vga associatedReset reset
set_interface_property vga ENABLED true

add_interface_port vga VGA_R r Output 8
add_interface_port vga VGA_G g Output 8
add_interface_port vga VGA_B b Output 8
add_interface_port vga VGA_CLK clk Output 1
add_interface_port vga VGA_HS hs Output 1
add_interface_port vga VGA_VS vs Output 1
add_interface_port vga VGA_BLANK_n blank_n Output 1
add_interface_port vga VGA_SYNC_n sync_n Output 1
